[Settings]
# Смени това с MAC адреса, който откри в предната стъпка!
TOKEN_MAC = 36:33:AB:AE:EB:AB

# Праг на RSSI, под който компютърът се заключва (напр. -80 dBm)
LOCK_THRESHOLD = -80

# Колко стойности назад да пазим за осредняване (колкото повече, толкова по-плавно, но по-бавно реагира)
MA_WINDOW_SIZE = 5

# Време в секунди. Ако токенът не е видян за това време, заключваме автоматично
TIMEOUT_SECONDS = 10