[Settings]
# Смени това с MAC адреса, който откри в предната стъпка!
# TOKEN_MAC = 36:33:AB:AE:EB:AB
TOKEN_MAC = 56:EE:51:EF:0D:B0
#TOKEN_MAC = 25:3B:72:6E:6B:29

# Праг на RSSI, под който компютърът се заключва (напр. -80 dBm)
LOCK_THRESHOLD = -90

# Колко стойности назад да пазим за осредняване (колкото повече, толкова по-плавно, но по-бавно реагира)
MA_WINDOW_SIZE = 5

# Време в секунди. Ако токенът не е видян за това време, заключваме автоматично
TIMEOUT_SECONDS = 10